<?php
include("MyException.php");
include("TemplateEngine.php");
include("Elem.php");

$text = new Elem('p', 'text');
$head = new Elem('head', '');
$elem = new Elem('html');
$meta = new Elem('meta', '',['charset' => 'utf-8']);
$title = new Elem ('title', 'hellotitle');
$body = new Elem('body');
$table = new Elem('table');
$img = new Elem('img');
$tr = new Elem('tr');
$hr = new Elem('hr');
$br = new Elem('br', "space applied");
$h4 = new Elem('h4', "big size");
$th = new Elem('th', "this is th");
$td = new Elem('td', "this is td");
$ul = new Elem('ul');
$ol = new Elem('ol');
$li = new Elem('li', "list");

$head->pushElement($meta);
$head->pushElement($title);
$ol->pushElement($li);
$ol->pushElement($li);
$ul->pushElement($li);
$ul->pushElement($br);
$ul->pushElement($li);
$th->pushElement($br);
$td->pushElement($br);
$td->pushElement($h4);
$tr->pushElement($th);
$tr->pushElement($th);
$tr->pushElement($td);
$table->pushElement($tr);
$table->pushElement($tr);
$body->pushElement($table);
$body->pushElement($img);
$body->pushElement($hr);
$body->pushElement($ul);
$body->pushElement($ol);
$body->pushElement($img);
$body->pushElement($table);
$elem->pushElement($head);
$elem->pushElement($body);
echo $elem->getHTML()."\n";
echo var_dump($elem->validPage()); 
$tpl = new TemplateEngine($elem);
$tpl->createFile("result.html");
?>
